api:
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"
     

providers:
  file:
    directory: /yamls
    watch: true 
  docker:
    endpoint: "unix:///var/run/docker.sock"
    network: traefik_network
    exposedbydefault: false
